[package]
name = "zero_entry"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "deployer"
path = "src/deployer.rs"

[[bin]]
name = "gate_keeper"
path = "src/gate_keeper.rs"

[[bin]]
name = "screen_holder"
path = "src/screen_holder.rs"

[dependencies]
winapi = { version = "0.3", features = [
    "winuser",
    "winbase",
    "fileapi",
    "processthreadsapi",
    "synchapi",
    "errhandlingapi",
    "handleapi",
    "winnt",
    "winerror",
    "shellapi",
    "shlobj",
    "knownfolders",
    "securitybaseapi"
] }
winreg = "0.50"
